labppw/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

story6/urls.py
from django.urls import path, include
from .views import status

app_name = "story6"

urlpatterns = [
    path('', status, name='status'),
]

story7/urls.py
from django.urls import path, include
from .views import story7_index

app_name = "story7"

urlpatterns = [
    path('', story7_index, name='story7_index'),
]

story8/urls.py
from django.urls import path, include
from .views import story8_index, get_book_list_JSON

app_name = "story8"

urlpatterns = [
    path('', story8_index, name='story8_index'),
    path('<str:value>' , get_book_list_JSON, name = "booklist"),
]

story9/urls.py
from django.urls import path, include
from .views import story9_index, logout_story9, register

app_name = "story9"

urlpatterns = [
    path('', story9_index, name='story9_index'),
    path('logout/', logout_story9, name='logout'),
    path('register/', register, name='register'),
]

story6/models.py
from django.db import models

# Create your models here.

class Status(models.Model):
    status_message = models.CharField(max_length=300)
    created_time = models.DateTimeField(auto_now_add=True)

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

story6/forms.py
from django import forms
from .models import Status

class StatusForm(forms.ModelForm):
    status_message = forms.CharField(widget=forms.Textarea(attrs={'cols': 10, 'rows': 20}))
    class Meta:
        model = Status
        fields = ['status_message']

story9/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Username',
        'type' : 'text',
        'required' : True
    }))
    password = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Password',
        'type' : 'password',
        'required' : True
    }))


class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Username',
        'type' : 'text',
        'required' : True
    }))
    email = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Email',
        'type' : 'text',
        'required' : True
    }))
    password = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'Password',
        'type' : 'password',
        'required' : True
    }))

story6/views.py
from django.shortcuts import render, HttpResponse, redirect
from .forms import StatusForm
from .models import Status

# Create your views here.
def status(request):
    if request.method == 'POST':
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('story6:status')
    else:
        form = StatusForm()

    response = {
        'form': form,
        'all_status': Status.objects.all().order_by('-id'),
    }

    return render(request, 'story6/index.html', response)

story7/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def story7_index(request):
    return render(request, 'story7/index.html', {})

story8/views.py
from django.shortcuts import render, HttpResponse
from django.http import JsonResponse
import urllib.request, json
import requests

# Create your views here.
def story8_index(request):
    return render(request, 'story8/index.html', {})

def get_book_list_JSON(request, value):
    data = requests.get("https://www.googleapis.com/books/v1/volumes?q="+value).json()
    return JsonResponse(data)

story9/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

from .forms import LoginForm, RegisterForm

# Create your views here
def story9_index(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            input_username = form.cleaned_data["username"]
            input_password = form.cleaned_data["password"]
            user_test = authenticate(request, username = input_username, password = input_password)
            if user_test is not None:
                login(request, user_test)
        return redirect("/story9/")
    form = LoginForm()
    response = {
        "form" : form
    }
    return render(request, "story9/index.html", response)

def logout_story9(request):
    logout(request)
    return redirect("/story9/")

def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if (form.is_valid()):
            input_username = form.cleaned_data["username"]
            input_email = form.cleaned_data["email"]
            input_password = form.cleaned_data["password"]
            try:
                user_temp = User.objects.get(username = input_username)
                return redirect("/story9/register/")
            except User.DoesNotExist:
                user_temp = User.objects.create_user(input_username, input_email, input_password)
                return redirect("/story9/")
    form = RegisterForm()
    response = {
        "form" : form
    }
    return render(request, "story9/register.html", response)

story6/templates/story6/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="black-background centering bg-changed1">
    <div class="container">
        <div>
            <h1>
                Halo, apa kabar?
            </h1>
        </div>
        <div>
            <form action="{% url 'story6:status' %}" method="POST">
                {% csrf_token %}
                {{ form.status_message }}
                <br>
                <br>
                <input type="submit" class="button b-green" value="Submit">
            </form>
        </div>
    </div>
</div>
<div class="white-background centering padding-top-3 bg-changed2">
    <div class="container">
        {% for status in all_status %}
        <div class="card w-100 b-black">
            <p class="small-font">{{ status.created_time }}</p>
            <h2 class="close-top">{{ status.status_message }}</h2>
        </div>
        <div class="spacing"></div>
        {% endfor %}
    </div>
</div>
{% endblock %}

story7/templates/story7/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="black-background bg-changed1">
    <div class="my-container">
        <div class="my-container d-flex flex-row align-items-center flex-wrap justify-content-center">
            <div class="mb-2">
                <img src="{% static 'story7/photo_rounded.png' %}" class="img-fluid" alt="image">
            </div>
            <div class="col">
                <p>
                    Interest in photography, end up with studying Computer Science and I loved it.
                    Currently developing my skills on <b>Web Developing</b> and <b>UI/UX</b>
                </p>
            </div>
        </div>
        <br>
        <div class="col-9">
            <div id="accordion-main">
                <h3 class="b-white b-changed-accordion" style="border:none;" name="acc-1">Activity</h3>
                <div class="b-white b-changed-accordion" style="border:none;">
                    <p>Currently doing something big!</p>
                </div class="b-white b-changed-accordion" style="border:none;">
                <h3 class="b-white b-changed-accordion" style="border:none;">Experience</h3>
                <div class="b-white b-changed-accordion" style="border:none;">
                    <ul>
                        <li><b>Deputy</b> of Media Bureau, BEM Fasilkom UI 2019</li>
                        <li><b>Owner</b> of Lex Ares Gamestore</li>
                    </ul>
                </div>
                <h3 class="b-white b-changed-accordion" style="border:none;">Achievement</h3>
                <div class="b-white b-changed-accordion" style="border:none;">
                    <ul>
                        <li><b>Runner Up</b> of IESPA Geforece I-Cafe Series #3 - CSGO</li>
                        <li>Other coming <b>really soon</b></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    {% block script %}
    <script src="{% static 'js/accordion.js' %}"></script>
    {% endblock %}
</div>
{% endblock %}

story8/templates/story8/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}book search{% endblock %}

{% block content %}
<div class="my-container black-background bg-changed1">
    <h1>Mini Book Search</h1>
    <form class="src-form" action="#">
        <input type="text" placeholder="write here" id="user-input">
        <button type="submit" id="search-button"><i class="fa fa-search"></i></button>
    </form>
    <br>
    <table class="table table-bordered white-background">
        <thead>
        <tr>
            <th scope="col">No</th>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">Cover</th>
        </tr>
        </thead>
        <tbody class="white-background b-white" id='book-result'>
            
        </tbody>

    </table>

    {% block script %}
    <script src="{% static 'js/searchbook.js' %}"></script>
    {% endblock %}
</div>
{% endblock %}

story9/templates/story9/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>{% block title %}gf - story{% endblock %}</title>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
      <link rel="stylesheet" href="/resources/demos/style.css">
      <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet" type='text/css'>
      <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'story9/css/style.css' %}">
  </head>
  <body>
      <div class="card">
        {% if user.is_authenticated == False %}
        <div class="win-sm">
          <h1>Masuk Kang</h1>
        </div>
        <div class="win-sm">
          <form method="POST">
            {% csrf_token %}
            <table>
              {{ form }}
            </table>
            <br>
            <button type="submit" class="button b-green" style="color:white !important;">Masuk</button>
            <a href="{% url 'story9:register' %}" class="button b-white ml-3">Daftar</a>
          </form>
        </div>
        {% elif user.is_authenticated == True %}
        <h1>Halo {{ user.username }}</h1>
        <a href="{% url 'story9:logout' %}" class="button b-white">Keluar</a>
        {% endif %}
      </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
    <script src="{% static 'js/theme.js' %}"></script>
  </body>
</html>

story9/templates/story9/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>{% block title %}gf - story{% endblock %}</title>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
      <link rel="stylesheet" href="/resources/demos/style.css">
      <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet" type='text/css'>
      <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'story9/css/style.css' %}">
  </head>
  <body>
      <div class="card">
        <div class="win-sm">
          <h1>Daftar Kang</h1>
        </div>
        <div class="win-sm">
          <form method="POST">
            {% csrf_token %}
            <table>
              {{ form }}
            </table>
            <br>
            <button type="submit" class="button b-green">Daftar</button>
          </form>
        </div>
      </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
    <script src="{% static 'js/theme.js' %}"></script>
  </body>
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}gf - story{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet" type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block style %}{% endblock %}
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light b-white color-navbar sticky-top">
        <a class="navbar-brand ml-5" href="#">ryaasabsar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse small-font" id="navbarNav">
            <ul class="navbar-nav ml-auto mr-5">
                <div class="ml-4">
                    <label class="switch">
                        <input type="checkbox" id="theme-button">
                        <span class="slider round"></span>
                    </label>
                </div>
                {% with url_name=request.resolver_match.url_name %}
                <li class="nav-item {% if url_name == 'status' %} active{% endif %} ml-4">
                    <a class="nav-link" href="{% url 'story6:status' %}">Status<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item ml-4 {% if url_name == 'story7_index' %} active{% endif %}">
                    <a class="nav-link" href="{% url 'story7:story7_index' %}">Profile</a>
                </li>
                <li class="nav-item ml-4 {% if url_name == 'story8_index' %} active{% endif %}">
                    <a class="nav-link" href="{% url 'story8:story8_index' %}">Book Search</a>
                </li>
                {% endwith %}
            </ul>
        </div>
    </nav>
    
    <!-- Content -->
    {% block content %}{% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
    <script src="{% static 'js/theme.js' %}"></script>
    {% block script %}{% endblock %}
  </body>
</html>